[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    Feature-Policy = "microphone 'none'; geolocation 'none'"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
